### ISSUE TITLE
Build instructions for Linux

### ISSUE THREAD

**Issue by BananaManCJ** [alexdillon/GroupMeClientAvalonia#18]
Does this have to be built with Visual Studio or can I build it natively on Linux?

**Comment by alexdillon** [comment]
Hey, sorry for taking so long to respond to this! I've had a lot going on, and haven't had time to work on this project much. I finally uploaded the README for it, which includes a section about building it with the dotnet CLI tools on Linux. It's been tested on Ubuntu 20.04LTS and 18.04LTS, but it should work on any version that supports .NET Core 3.1 SDK.
